# Generated by Django 5.2.4 on 2025-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayAnchor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='pi_number',
            field=models.CharField(default='RP', max_length=2),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='reference_number',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
