# Generated by Django 5.2.4 on 2025-08-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayAnchor', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='postal_code',
            field=models.CharField(default='111111', max_length=7),
        ),
    ]
